# Generated by Django 5.2 on 2025-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='hobbies',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
